version: "2.4"
services:
  dev_backend:
    image: docker.pkg.github.com/rruss/comments-api/comments:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - "./media:/code/media"
